#include <iostream>
#include <
using namespace std;

int main(){
  int opc;
 system("clear");
 cout<<"Made by Arkou#7004\n";
 system("run https://discord.gg/GAmQQpXmS3");
 cout<<"open menu [1] \n";
 cout<<">>>> ";
  
 cin>>opc;

  if(opc == 1){
    int opc2;
    system("clear");
    cout<<"[1]Open porhub.com\n";
    cout<<"[2]Explode pc\n";
    cout<<"[3]Explode memory\n";
    cout<<">>>> ";
    cin>>opc2;
    switch(opc2){
      system("clear");
      case 1: cout<<"opening";
      system("run porhub.com");
      break;
      case 3: cout<<"exploding\n";
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      system("cmd");
      break;

      
      case 2:
        system("clear");
        cout<<"exploting";
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
               system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
               system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
               system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
               system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
               system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
               system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
               system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
               system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
               system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
        system("run xvideos.com");
      break;
      
      default :
      system("clear");
      cout<<"Invalid";
      break;
    }




    
  }

 else{
 system("clear");
 cout<<"\nInvalid";
 }





  return 0;
}